/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.util.ArrayList;
import model.EmployeeInfo;

/**
 *
 * @author ikrabagwan
 */
public class DisplayAllEmployees extends javax.swing.JFrame {

    /**
     * Creates new form DisplayAllEmployees
     */
    ArrayList<EmployeeInfo> employeeArray;
    public DisplayAllEmployees(ArrayList<EmployeeInfo> employeeArray) {
        this.employeeArray = employeeArray;
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeinformation = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Employee Information ");

        employeeinformation.setModel(new javax.swing.table.DefaultTableModel(
            employeeTableInfo(),

            new String [] {
                "Name", "EmployeeId", "StartDate", "Level" , "Age" , "Gender" ,
                "Email" , "Telephone" , "PositionTitle" , "TeamInfo"
            }
        ));
        jScrollPane1.setViewportView(employeeinformation);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 567, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public Object[][] employeeTableInfo(){
        
        String info[][] = new String[this.employeeArray.size()][10];
        
        for(int i = 0; i < this.employeeArray.size(); i++){
        EmployeeInfo emp = this.employeeArray.get(i);
        String empData[] = new String[10];
            empData[0] = emp.getName();
            empData[1] = String.valueOf(emp.getEmployeeId());
            empData[2] = String.valueOf(emp.getStartDate());
            empData[3] = emp.getLevel();
            empData[4] = String.valueOf(emp.getAge());
            empData[5] = emp.getGender();
            empData[6] = emp.getEmail();
            empData[7] = String.valueOf(emp.getTelephone());
            empData[8] = emp.getPositionTitle();
            empData[9] = emp.getTeamInfo();
            
            
            info[i] = empData;
        
        }
        
//        "Name", "EmployeeId", "StartDate", "Level" , "Age" , "Gender" ,
        //"Email" , "Telephone" , "PositionTitle" , "TeamInfo" ,"Photo" ,
    

        return info;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable employeeinformation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
